### ISSUE TITLE
Avoid `quick-peek-background-face`

### ISSUE THREAD

**Issue by xiongtx** [cpitclaudel/quick-peek#4]
## Expected behavior

It should be possible to use `quick-peek-show` without applying `quick-peek-background-face` to input text.

## Actual behavior

`quick-peek-background-face` is [always applied](https://github.com/cpitclaudel/quick-peek/blob/master/quick-peek.el#L156) by `quick-peek--prepare-for-definition-overlay`.

## Steps to reproduce

Evaluate the following:

```emacs-lisp
(quick-peek-show (propertize "foo" 'font-lock-face 'font-lock-doc-face))
```

`foo` is *not* shown with `font-lock-doc-face`, but `quick-peek-background-face` instead.

Using a `face` property instead of `font-lock-face` *does* override `quick-peek-background-face` if `quick-peek-background-face` is set to `undefined` for all face attributes, but the user cannot always guarantee that `face` instead of `font-lock-face` is used.

Also see [Emacs StackExchange question](https://emacs.stackexchange.com/questions/32801/how-to-create-face-that-passes-through).

## Backtraces if necessary (`M-x toggle-debug-on-error`)

N/A

## Versions of `centered-window-mode`, Emacs, OS etc.

- `quick-peek`: `20170327.27`
- Emacs: `25.1.1`
- OS: `Fedora 24`

**Comment by cpitclaudel** [comment]
Thanks for the report. Can you give a concrete example where this is a problem, though?  You write 

> but the user cannot always guarantee that face instead of font-lock-face is used.

Which is true, but I'm not seeing clearly why this is a problem.

Thanks!

**Comment by xiongtx** [comment]
If you evaluate the example with `quick-peek-background-face` set to `undefined` for all attributes,  the text will *not* be displayed with `font-lock-doc-face` b/c it's propertized w/ `font-lock-face`, not `face`.

**Comment by cpitclaudel** [comment]
Right, but where concretely did this example come from?

**Comment by xiongtx** [comment]
One example is the output of [`cider-docview-render-info`](https://github.com/clojure-emacs/cider/blob/v0.14.0/cider-doc.el#L379) from [CIDER](https://github.com/clojure-emacs/cider), the Clojure development environment.

**Comment by cpitclaudel** [comment]
Thanks, that's very helpful.  I think I understand the problem better now. I'll answer in the other thread.
