### ISSUE TITLE
auto hide quick-peek overlay

### ISSUE THREAD

**Issue by stardiviner** [cpitclaudel/quick-peek#7]
I have similar library to show inline docs https://github.com/stardiviner/inline-docs.el
I use it in package [eldoc-overlay-mode](https://github.com/stardiviner/eldoc-overlay-mode). I wish be able to use `quick-peek` in eldoc-overlay-mode.
But quick-peek does not auto remove overlay. Hope to add this function.

**Comment by cpitclaudel** [comment]
Thanks! Good to hear from you. Does running quick-peek-hide work? Or am I misunderstanding your request?

**Comment by stardiviner** [comment]
Yes, I tried a workaround with `(add-hook 'post-command-hook 'quick-peek-hide)`. I use this way in my `inline-docs` too. Thanks.
